version: '3'

services:
 python_backend:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   volumes: ["./python_backend:/opt/python_backend"]
   environment:
     PORT: "5000"
     FLASK_DEBUG: "true"
   ports:
     - "5000:5000"
